print("Welcome to the Band Name Generator")
print("Whats the name of the city you grew up in?")
CName = str(input())
print("Whats your pet's name?")
PName = str(input())
print("Your band name could be " + CName + " " + PName)